from agents import (
    Agent,
    FileSearchTool,
    InputGuardrail,
    GuardrailFunctionOutput,
    Runner,
    RunContextWrapper,
    handoff,
)
from agents.exceptions import InputGuardrailTripwireTriggered
from agents.extensions.visualization import draw_graph
from agents.extensions.handoff_prompt import RECOMMENDED_PROMPT_PREFIX
from pydantic import BaseModel
import asyncio
from pathlib import Path
import os


# Import plotting tools
from ecooptima_tools import plot_bar_chart, _generate_timestamp  # , plot_pie_chart


###############
### GLOBALS ###
###############
def _prompt_generator(task, tool):
    return f"""SYSTEM CONSTRAINTS (MANDATORY):
This is a routing-only task.

The assistant MUST:
- Produce exactly ONE tool call
- Call ONLY the '{tool}' tool
- Do not produce any tokens after the tool call

The assistant MUST NOT:
- Answer the user
- Provide analysis, explanations, tables, charts, or text
- Provide status updates
- Output anything outside the tool call

Any output other than a single '{tool}' tool call is INVALID.

TASK:
{task}

ACTION:
Immediately call '{tool}'"""


# Model each acgent will use
agent_model = "gpt-5-nano"

# Vector store ID for the plant matrix file on the OpenAI Platform
plant_matrix_vector_store = "vs_6910105ece0c81918f2371e0f6c32696"


# Optional function to perform an action on handoff - keeping as an example for now
async def on_handoff(ctx: RunContextWrapper[None], input_data):
    print(input_data)


# Structured output base class
# Used by plant_matrix_agent and extended by planting_benefits_agent
class RankedSpecies(BaseModel):
    species: str
    size: str
    survivial_probability: str
    maintenance_costs: str


################1#########
### USER-FACING AGENT ###
#########################

user_facing_agent = Agent(
    name="User Facing Agent",
    model=agent_model,
    instructions="""You are the final agent in a multi-agent workflow. Your job is to translate the response
                    generated by the other agents into plaintext so the user can understand it. Give a consise 
                    plant recommendation list and use the plot_bar_chart tool to generate a marginal abatement
                    cost curve to give an overview of the plant choices vs. benefits presented to the user.

                    For reference: a MACC shows how much it costs to reduce one additional unit of pollution, 
                    ranking abatement options from cheapest to most expensive and indicating how much reduction 
                    each option can deliver.

                    You MUST return both the plaintext summary and ONE MACC.""",
    output_type=str,
    tools=[
        FileSearchTool(vector_store_ids=[plant_matrix_vector_store]),
        plot_bar_chart,
        # plot_pie_chart,
    ],
)


#######################
### LOCAL ROI AGENT ###
#######################


class RankedSpeciesForROI(RankedSpecies):
    carbon_sequestration: str
    stormwater_inception: str
    heat_island_mitigation: str
    air_quality_benefit: str
    well_being_benefit: str
    cooling_cost_savings: str


class LocalROIResult(BaseModel):
    rankings: list[RankedSpeciesForROI]


user_facing_agent_handoff = handoff(
    agent=user_facing_agent,
    on_handoff=on_handoff,
    input_type=LocalROIResult,
    tool_name_override="user_facing_agent_handoff",
)


local_roi_agent = Agent(
    name="Local ROI Advisor",
    model=agent_model,
    instructions=_prompt_generator(
        "Quantify local ROI (air_quality_benefit, well_being_benefit, heat_island_mitigation, cooling_cost_savings) for the provided plant list using vector store lookup.",
        "user_facing_agent_handoff",
    ),
    # output_type=LocalROIResult,
    tools=[
        FileSearchTool(vector_store_ids=[plant_matrix_vector_store]),
        # plot_bar_chart,
        # plot_pie_chart,
    ],
    handoffs=[user_facing_agent_handoff],
)


###############################
### PLANTING BENEFITS AGENT ###
###############################


class RankedSpeciesForBenefits(RankedSpecies):
    carbon_sequestration: str
    stormwater_inception: str


class PlantingBenefitsResult(BaseModel):
    rankings: list[RankedSpeciesForBenefits]


local_roi_handoff = handoff(
    agent=local_roi_agent,
    on_handoff=on_handoff,
    input_type=PlantingBenefitsResult,
    tool_name_override="local_roi_handoff",
)


plant_benefits_agent = Agent(
    name="Planting Benefits Advisor",
    model=agent_model,
    instructions=_prompt_generator(
        "Quantify environmental benefits (carbon sequestration and stormwater interception) for the provided plant list using vector store lookup.",
        "local_roi_handoff.",
    ),
    tools=[
        FileSearchTool(vector_store_ids=[plant_matrix_vector_store]),
        # plot_bar_chart,
        # plot_pie_chart,
    ],
    handoffs=[local_roi_handoff],
)


##########################
### PLANT MATRIX AGENT ###
##########################


class PlantMatrixResult(BaseModel):
    rankings: list[RankedSpecies]


planting_benefits_handoff = handoff(
    agent=plant_benefits_agent,
    on_handoff=on_handoff,
    input_type=PlantMatrixResult,
    tool_name_override="planting_benefits_handoff",
)

plant_matrix_agent = Agent(
    name="Plant Matrix Advisor",
    model=agent_model,
    handoff_description="Specialist agent for plant matrix",
    instructions=_prompt_generator(
        "Use the FileSearchTool on the vector store to create a ranked list of plants including size, survivial_probability, and maintenance_costs based on the input variables",
        "planting_benefits_handoff",
    ),
    tools=[
        FileSearchTool(vector_store_ids=[plant_matrix_vector_store]),
        # plot_bar_chart,
        # plot_pie_chart,
    ],
    handoffs=[planting_benefits_handoff],
)


#######################
### GUARDRAIL AGENT ###
#######################


# TypedDict for guardrail output
class GuardrailOutput(BaseModel):
    is_eco_optima: bool  # whether the input is related to plants
    reasoning: str  # reasoning for the determination


# Define guardrail sub-agent: https://openai.github.io/openai-agents-python/guardrails/
guardrail_agent = Agent(
    name="Guardrail",
    model=agent_model,
    instructions="""Check if the user is asking about plants. 
                    Output a one sentence response classifying it as related to EcoOptima 
                    or not and a boolean value accordingly.""",
    output_type=GuardrailOutput,
)


# Define guardrail function to be called by the triage_agent
async def eco_optima_guardrail(ctx, agent, input_data):
    result = await Runner.run(guardrail_agent, input_data)
    final_output = result.final_output_as(GuardrailOutput)

    # Check if tripwire was triggered and return appropriate GuardrailFunctionOutput
    return GuardrailFunctionOutput(
        output_info=final_output,
        tripwire_triggered=not final_output.is_eco_optima,
    )


####################
### TRIAGE AGENT ###
####################


# Output structure to pass to plant_matrix_agent
class InputVariables(BaseModel):
    user_location: str | None = None
    project_type: str | None = None
    scale: str | None = None
    time_horizon_years: str | None = None
    budget: str | None = None


# Handoff object to execute information relay
plant_matrix_handoff = handoff(
    agent=plant_matrix_agent, on_handoff=on_handoff, input_type=InputVariables
)


# Define triage agent
triage_agent = Agent(
    name="Triage Agent",
    model=agent_model,
    instructions="""You use the given query and map it to the following variables (leave any variables that are not mentioned in the query blank):
                    user_location = Cincinnati, Ohio
                    project_type = [what the desired project is (tiny forest, street trees, schoolyard, etc...)]
                    scale = [size of project (for a park, a neighborhood, a city, a university, etc...)]
                    time_horizon_years = [how long the user wants project SETUP will take, not including continuous maintenance]
                    budget = [total budget for project]

                    Then, call the plant_matrix_handoff tool to pass the information to the next agent. Do not give a final response
                    to the user.""",
    input_guardrails=[InputGuardrail(guardrail_function=eco_optima_guardrail)],
    handoffs=[plant_matrix_handoff],
)

############################
### GRAPHVIZ AND LOGGING ###
############################


# Visualize agent graph using Graphviz: https://openai.github.io/openai-agents-python/visualization/
draw_graph(triage_agent, filename="agent_graph")


# Response logging structure
class RunLog:
    timestamp: str
    input: str
    response: str


#####################
### MAIN FUNCTION ###
#####################


# Main function to run the agent
async def main(user_text):
    while True:
        try:
            user_input = user_text

            # Exit condition
            if user_input.strip().lower() == "exit":
                break

            RunLog.timestamp = _generate_timestamp()
            log_dir = Path("response_log") / RunLog.timestamp
            log_dir.mkdir(parents=True, exist_ok=True)
            os.environ["ECOOPTIMA_LOG_DIR"] = str(log_dir)

            result = await Runner.run(triage_agent, user_input)
            print(result)
            return result.final_output

        except InputGuardrailTripwireTriggered as e:
            print("Guardrail blocked this input: ", e)
            return str(e)

        # Log the run
        #        RunLog.input = user_input
        #        RunLog.response = result.final_output
        #        (log_dir / "input.txt").write_text(RunLog.input, encoding="utf-8")
        #        (log_dir / "output.txt").write_text(RunLog.response, encoding="utf-8")


if __name__ == "__main__":
    input = input("Query: ")
    result = asyncio.run(main(input))
    print(result)
